#!/usr/bin/env bash

# Exit if any subcommand fails
set -e

# Compile unoptimized assets
smash compile

# Sync with remote host
rsync -av -e ssh compile/ deployer@$1.bellwetherinsights.com:bwi-web-client/compile/
